version: "3.8"

services:
  server:
    build: ./server
    container_name: magiccoupon-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/magiccoupon
      - JWT_SECRET=your_jwt_secret_here
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - GOOGLE_CALLBACK_URL=https://magiccoupon-backend.onrender.com/auth/google/callback
    depends_on:
      - mongo
    restart: unless-stopped

  client:
    build: ./client
    container_name: magiccoupon-client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: magiccoupon-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=magiccoupon
    restart: unless-stopped

volumes:
  mongo-data:
