version: "3.8"

services:
  server:
    build: ./server
    container_name: magiccoupon-server-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/magiccoupon
      - JWT_SECRET=dev_jwt_secret
      - GOOGLE_CLIENT_ID=dev_google_client_id
      - GOOGLE_CLIENT_SECRET=dev_google_client_secret
      - GOOGLE_CALLBACK_URL=http://localhost:5000/auth/google/callback
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    command: npm run dev

  client:
    build: ./client
    container_name: magiccoupon-client-dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped
    command: npm start

  mongo:
    image: mongo:7
    container_name: magiccoupon-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=magiccoupon
    restart: unless-stopped

volumes:
  mongo-data-dev:
